### ISSUE TITLE
Scanner not identifying DC 2021 Annual file

### ISSUE THREAD

**Issue by Webby2687** [mylar3/mylar3#1040]
**Describe the bug**
I'm trying to clean up my Batman (2016) files and have added both series of annuals to the main Batman (2016) series page. The original 5 annuals in the traditional numbering sequence are detected by the scanner and are fine. The new 2021 Annual is not. I've tried re-naming the file a number of different ways and cannot get the scanner to identify it.

Is there a standard naming convention I should use for these annuals?
![image](https://user-images.githubusercontent.com/47880626/152396969-6f5f9241-e975-4107-aab4-63405dd1f45c.png)

![image](https://user-images.githubusercontent.com/47880626/152397091-a64e9136-2574-4415-9c06-475e69866f6c.png)

**CarePackage**
https://drive.google.com/file/d/1xox66k5gDw5-Yd85REnN_nyda7hlKov5/view?usp=sharing 

**Environment (please complete the following information):**
 - OS: Windows 10
 - Branch / commit: Master / [4a54f5f28d587b4f877ad163cae36f27d42c3135]

**Comment by evilhero** [comment]
The version of Mylar you are running is over 4 months old.

Update to the latest version and see if that fixes things.

**Comment by Webby2687** [comment]
Thanks Evilhero, I did run the update function but the version isn't updating. Is there a way for me to manually update? 

Here is the log for my update that failed:

03-Feb-2022 13:22:51 - INFO :: mylar.checkGithub.279 : CP Server Thread-13 : New version is available. You are 52 commits behind
03-Feb-2022 13:23:31 - INFO :: mylar.configure.1077 : CP Server Thread-16 : Ignored Publishers: []
03-Feb-2022 13:23:31 - INFO :: mylar.configure.1100 : CP Server Thread-16 : [MASS_PUBLISHERS] Auto-add for weekly publishers set to: []
03-Feb-2022 13:23:31 - INFO :: mylar.configure.1112 : CP Server Thread-16 : [PROBLEM_DATES] Problem dates loaded: ['2021-07-14 04:00:34']
03-Feb-2022 13:23:31 - INFO :: mylar.configure.1116 : CP Server Thread-16 : [COMICTAGGER] Version detected: 1.3.4
03-Feb-2022 13:23:31 - INFO :: mylar.configUpdate.6894 : CP Server Thread-16 : Now saving config...
03-Feb-2022 13:23:37 - INFO :: mylar.main.377 : MAIN : Received signal: update
03-Feb-2022 13:23:40 - INFO :: mylar.halt.1500 : MAIN : Shutting down the background schedulers...
03-Feb-2022 13:23:40 - INFO :: mylar.shutdown.1529 : MAIN : Mylar is updating...
03-Feb-2022 13:23:41 - ERROR :: mylar.runGit.54 : MAIN : Encountered error: From https://github.com/mylar3/mylar3
 * branch              master     -> FETCH_HEAD
error: Your local changes to the following files would be overwritten by merge:
        Mylar.py
        data/css/style.css
        data/interfaces/carbon/css/data_table.css
        data/interfaces/carbon/css/style.css
        data/interfaces/default/base.html
        data/interfaces/default/config.html
        data/interfaces/default/css/data_table.css
        data/interfaces/default/css/style.css
        data/interfaces/default/history.html
        data/interfaces/default/importresults.html
        data/interfaces/default/index.html
        data/interfaces/default/manage.html
        data/interfaces/default/managecomics.html
        data/interfaces/default/managefailed.html
        data/interfaces/default/manageissues.html
        data/interfaces/default/readinglist.html
        data/interfaces/default/searchresults.html
        data/interfaces/default/storyarc.html
        data/interfaces/default/storyarc_detail.html
        data/interfaces/default/storyarc_detail.poster.html
        data/interfaces/default/upcoming.html
        data/interfaces/default/weeklypull.html
        data/js/script.js
        lib/certgen.py
        mylar/PostProcessor.py
        mylar/__init__.py
        mylar/api.py
        mylar/auth.py
        mylar/carepackage.py
        mylar/cmtagmylar.py
        mylar/config.py
        mylar/cv.py
        mylar/encrypted.py
        mylar/filechecker.py
        mylar/filers.py
        mylar/getimage.py
        mylar/helpers.py
        mylar/importer.py
        mylar/mb.py
        mylar/nzbget.py
        mylar/rsscheck.py
        mylar/sabnzbd.py
        mylar/search.py
        mylar/updater.py
        mylar/webserve.py
        mylar/weeklypull.py
Please commit your changes or stash them before you merge.
Aborting

03-Feb-2022 13:23:41 - INFO :: mylar.shutdown.1540 : MAIN : Mylar is restarting...
03-Feb-2022 13:23:41 - INFO :: mylar.shutdown.1548 : MAIN : Restarting Mylar with ['C:\\Program Files\\Python39\\python.exe', 'C:\\mylar3\\Mylar.py']
log language set to en_US
Initializing startup sequence....
03-Feb-2022 13:23:41 - INFO :: mylar.configure.1077 : MainThread : Ignored Publishers: []
03-Feb-2022 13:23:41 - INFO :: mylar.configure.1100 : MainThread : [MASS_PUBLISHERS] Auto-add for weekly publishers set to: []
03-Feb-2022 13:23:41 - INFO :: mylar.configure.1112 : MainThread : [PROBLEM_DATES] Problem dates loaded: ['2021-07-14 04:00:34']
03-Feb-2022 13:23:41 - INFO :: mylar.configure.1116 : MainThread : [COMICTAGGER] Version detected: 1.3.4
03-Feb-2022 13:23:41 - INFO :: mylar.initialize.209 : MainThread : Checking to see if the database has all tables....
03-Feb-2022 13:23:41 - INFO :: mylar.dbcheck.1462 : MainThread : Ensuring DB integrity - Removing all Erroneous Comics (ie. named None)
03-Feb-2022 13:23:41 - INFO :: mylar.dbcheck.1472 : MainThread : Correcting Null entries that make the main page break on startup.
03-Feb-2022 13:23:41 - INFO :: mylar.initialize.223 : MainThread : Successfully discovered local IP and locking it in as : 10.5.0.2
03-Feb-2022 13:23:41 - INFO :: mylar.initialize.299 : MainThread : [IMPRINT_LOADS] Loading Publisher imprints data from local file.
03-Feb-2022 13:23:41 - INFO :: mylar.initialize.325 : MainThread : [IMPRINT_LOADS] Successfully loaded imprints for 6 publishers
03-Feb-2022 13:23:41 - INFO :: mylar.initialize.335 : MainThread : Remapping the sorting to allow for new additions.
03-Feb-2022 13:23:41 - INFO :: mylar.ComicSort.754 : MainThread : Sucessfully ordered 1727 series in your watchlist.
03-Feb-2022 13:23:41 - INFO :: mylar.validateAndCreateDirectory.1766 : MainThread : [DIRECTORY-CHECK] Found comic directory: C:\mylar3
[AUTO-BACKUP] Backing up .db and config.ini files for safety.
[AUTO-BACKUP] Now Backing up C:\mylar3\backup\mylar.db file
[AUTO-BACKUP] C:\mylar3\backup\mylar.db.1 exists. Deleting and keeping new.
[AUTO-BACKUP] Now renaming C:\mylar3\backup\mylar.db to C:\mylar3\backup\mylar.db.1
[AUTO-BACKUP] Now copying db file to C:\mylar3\backup\mylar.db
[AUTO-BACKUP] Now Backing up C:\mylar3\backup\config.ini file
[AUTO-BACKUP] C:\mylar3\backup\config.ini.1 exists. Deleting and keeping new.
[AUTO-BACKUP] Now renaming C:\mylar3\backup\config.ini to C:\mylar3\backup\config.ini.1
[AUTO-BACKUP] Now copying db file to C:\mylar3\backup\config.ini
03-Feb-2022 13:23:41 - INFO :: mylar.getVersion.131 : MAIN : cur_commit_hash: 4a54f5f28d587b4f877ad163cae36f27d42c3135
03-Feb-2022 13:23:41 - INFO :: mylar.getVersion.132 : MAIN : cur_branch: master
03-Feb-2022 13:23:41 - INFO :: mylar.getVersion.162 : MAIN : Branch detected & set to : master
03-Feb-2022 13:23:41 - INFO :: mylar.versionload.393 : MAIN : Version information: master [4a54f5f28d587b4f877ad163cae36f27d42c3135]
03-Feb-2022 13:23:41 - INFO :: mylar.initialize.73 : MAIN : Starting Mylar on http://0.0.0.0:8090/
03-Feb-2022 13:23:43 - INFO :: mylar.start.432 : MAIN : [DB UPDATER] DB Updater scheduled to run immediately.
03-Feb-2022 13:23:43 - INFO :: mylar.queue_schedule.602 : MAIN : [SEARCH-QUEUE] Attempting to background load the search queue....
03-Feb-2022 13:23:43 - INFO :: mylar.queue_schedule.605 : MAIN : [SEARCH-QUEUE] Successfully started the Search Queuer...
03-Feb-2022 13:23:43 - INFO :: mylar.start.482 : MAIN : [WEEKLY] Checking for existance of Weekly Comic listing...
03-Feb-2022 13:23:43 - INFO :: mylar.start.548 : MAIN : Firing up the Background Schedulers now....
03-Feb-2022 13:23:43 - INFO :: mylar.start.552 : MAIN : Background Schedulers successfully started...
03-Feb-2022 13:23:43 - INFO :: mylar.watchlist_updater.1913 : ThreadPoolExecutor-0_0 : [BACKFILL-UPDATE] Update ran < 15 minutes ago. Not running.

**Comment by evilhero** [comment]
The below is assuming you haven't done any local changes to your install. 

Assuming you're on master, and you installed via git - then you probably need to do the following commands from a command line and be at the root of the mylar installation:

```
git fetch

git checkout master

git reset --hard origin/master

```
And possibly a ``git pull`` after the last step.

**Comment by Webby2687** [comment]
Thank you!

It looks like that did update the version (although on the settings page in the UI it says the version is 'none' and I'm getting a warning about an unknown version. I am seeing the branch history show the latest commits from 4 weeks ago though and the python script shows me on version fce4771c5b627f8de6868dd4ab6bc53f7b22d303)

![image](https://user-images.githubusercontent.com/47880626/152431904-7f95ade9-106d-4025-9789-ed3cc3dfc0b7.png)

After the update though I'm still not getting the scanner to pick up the annuals. Do you want me to upload a new care package?

**Comment by evilhero** [comment]
In your config.ini make sure you set  ``git_branch = master`` and ``git_user = mylar3``(with mylar not running), and that should fix the None problem - you might have to do a check for version / update via the GUI for it to reconfigure if just setting the variables don't fix it.

The parsing of the filename will depend on how you have it named now - it should be named as per the annual series ``Batman 2021 Annual #01 (December, 2021)``.  I know we patched some annual stuff in the dev branch, but that was more cause we broke things. The ``December, 2021`` might be throwing it off cause of it being listed as 2022...but if the naming is fine and it's not picking it up then yes carepackage with debug enabled prior to file checking would help.

**Comment by Webby2687** [comment]
Ah yeah looks like it was the December, 2021 as the problem, I forgot to tweaked that as part of my testing to see the 2022 in the year was causing confusion for the scanner. Thank you!

Last thing for the version, in the Config.ini I updated git_branch = master (the git_user was already correct), saved, launched Mylar and did the check for new version/update and it's still not identifying the version. Could it be the git_token = None is the problem?

Here is the Git section of the config file:
[Git]
git_user = mylar3
check_github = False
git_path = None
check_github_on_startup = False
git_branch = master
git_token = None

**Comment by evilhero** [comment]
Yeah there are some glitches with the version check that we're currently working thru in dev - can you try setting  ``check_github_on_startup = True`` and see if that fixes things?

**Comment by Webby2687** [comment]
That fixed it, thank you again!
