### ISSUE TITLE
Exception in search blocks all new searches until mylar is restarted

### ISSUE THREAD

**Issue by miracle152005** [mylar3/mylar3#352]
**Describe the bug**
If a exception happens in while doing a search the user is unable to search again until mylar is restarted. Searches are just added to the queque and kept there.
The queque should be freed of the failing job and allow new jobs to run.

**Debug Log**
[mylar.log](https://github.com/mylar3/mylar3/files/4808559/mylar.log)

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04
 - Branch / commit: 6c7f547b48113c402ac167466f1ada3f19d98932

**Comment by barbequesauce** [comment]
related to #353

**Comment by evilhero** [comment]
This was also addressed in #343 where I basically explained the concept behind a traceback error  - and that it's almost impossible to account for every variation, which is why we ask for bug reports. 

Was that answer not up to snuff or something?

**Comment by miracle152005** [comment]
@evilhero :
I understand your reasoning behind traceback errors.
But I still think this should be handled gracefully instead of breaking the application until the next restart.
The most easy way to "handle" it would be to catch all exception in search_queque. Log the tracebackerror and in the finally block release the searchblock.
This way you still have the exception for the failed item but further searches still work.

**Comment by miracle152005** [comment]
I created a pull request:
https://github.com/mylar3/mylar3/pull/355

Which resolves the issue by logging the exception in searchforissue and resetting the searchlock in a finally.

**Comment by barbequesauce** [comment]
Are we ok to close?

**Comment by miracle152005** [comment]
I am ok with it not getting fixed. But there is no indicator in the Ui if the search is in a failed state. Only possibility is to search in the logs if you suspect that could be the case. Could we maybe create an improvement that sets the state of the task to failed if it will no longer be able to run without restarting the application?

**Comment by barbequesauce** [comment]
Sorry - i saw the PR was closed, forgot evilhero had a fix to push... stay tuned

**Comment by barbequesauce** [comment]
Closing due to staleness, we welcome contributions for new features. If this is an issue and you are still experiencing it, please open a new ticket with a care package attached.
