### ISSUE TITLE
Post Processing not working correctly even if file is exactly the same name as series

### ISSUE THREAD

**Issue by miracle152005** [mylar3/mylar3#786]
**Describe the bug**
Hi,
I have multiple files which can no longer be post processed even though the name should be exactly right. 
In this example it is Betty and Veronica Double Digest 294 or DC Horror Presents - The Conjuring - The Lover 01.
I am getting the following message in log:
"Betty and Veronica Double Digest 294 in filename don't match up to what's in the dB Betty and Veronica Double Digest 294 [28073]"

Could you please take a look.
Thanks.

Best regards miracle152005

**CarePackage**
[mylar.log](https://github.com/mylar3/mylar3/files/6660391/mylar.log)

**Environment (please complete the following information):**
 - OS: ubuntu 18.04 (docker)
 - Branch / commit: [ae446d119ad239b1fbddb891942cc61bf39f15f1]

**Comment by evilhero** [comment]
Should be resolved in latest python3-dev branch.

**Comment by miracle152005** [comment]
still happening on 0f5a891391877911008ac74b5aad9a6b4380d799

**Comment by evilhero** [comment]
Recreate the pull for the week those particular issues are on. Make sure the status says Wanted. If it doesn't flip to the series to see if it has issue data for that issue. Try post-processing it again after the recreate.

**Comment by miracle152005** [comment]
Recreating the pull list for the week does not do anything. The issue is kept in "Snatched" state and the issue still happens.
Setting it manually to wanted just downloads the issue again and we are at the same state as before

**Comment by miracle152005** [comment]
It worked for Betty and Veronica but not for DC Horror Presents - The Conjuring - The Lover 01.
Every issue which does not work, that i currently found, have a ":" in the title of the series.

**Comment by evilhero** [comment]
Try to recreate your pull again for that specific week ( you'd have to be viewing the specific week when you hit the recreate button for it to recreate properly ).

I just tested and it was able to download and post-process the issue with no problems. I also tried a manual post-processing and that worked fine as well.

**Comment by miracle152005** [comment]
It now worked for DC Horror Presents - The Conjuring - The Lover 01, but not for Demon Days Mariko 001.

**Comment by evilhero** [comment]
Tested both downloading & manually post-processing Mariko - works fine for both attempts with no errors. Try recreating your pull for that specific week again.

**Comment by miracle152005** [comment]
tried it 5 times already. Same result every time.

**Comment by evilhero** [comment]
You recreated the pull when viewing that specific week ? Not sure what to tell you - had no issues with either aspect when I just added it and post-processed. They just updated the series last night on CV - maybe try to refresh the series and then attempt to do a post-process.

Other than that - need logs, but not sure when I can look into it as I'm knee deep in stuff atm...

**Comment by miracle152005** [comment]
ok, refresh worked for all but one series:
ExtraOrdinary 0 which has a completly different name on the weekly list and ist listed there as "V.E. Schwab's Extraordinary 0". Its not even mapped on the weekly list.

https://comicvine.gamespot.com/extraordinary/4050-135879/

**Comment by evilhero** [comment]
It's updated on the backend - it will be in your pullist in a few hours at most (probably the next time it auto-recreates the pull).

Closing this now as now we're getting into CV naming / delay territory and not regarding post-processing.
